---
abstract: 'create URL slugs from text'
author:
  - 'Robert Norris <rob@eatenbyagrue.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Slugify
requires:
  Exporter: '0'
resources:
  bugtracker: https://github.com/robn/Text-Slugify/issues
  repository: git://github.com/robn/Text-Slugify.git
version: '0.001'
